Repository flutter/photobooth, pull requests merged in 2021-05, with the labels that each got.

#627 docs: update README links
  README.md
Labels: documentation

#629 ci: enable sharing in dev
  .github/workflows/deploy.yaml
Labels: ci

#637 feat: add various semantics labels
  lib/l10n/arb/app_en.arb
  lib/photobooth/widgets/characters_caption.dart
  lib/photobooth/widgets/photobooth_preview.dart
  lib/photobooth/widgets/shutter_button.dart
  lib/share/view/share_page.dart
  lib/stickers/view/stickers_page.dart
  lib/stickers/widgets/clear_stickers/clear_stickers_button_layer.dart
Labels: wip

#643 fix: typo of mentiones -> mentions
  lib/l10n/arb/app_en.arb
Labels: documentation
